stages:
  - build
  - deploy

Fastapi_image_build:
  stage: build
  script:
    - echo "FastApi build, Dockerfile:"
    - export Sql_URL="mysql://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DB_NAME?charset=utf8mb4"
    - cat Dockerfile
    - echo Sql_URL
    - docker build --build-arg Sql_URL=${Sql_URL} -t hub.exploit-db.xyz/fastapi:$CI_PIPELINE_ID .
    - docker tag hub.exploit-db.xyz/fastapi:$CI_PIPELINE_ID hub.exploit-db.xyz/fastapi:latest
    - docker push hub.exploit-db.xyz/fastapi:$CI_PIPELINE_ID
    - docker push hub.exploit-db.xyz/fastapi:latest

Fastapi_swarm_deploy:
  stage: deploy
  script:
    - echo "Deploying to Docker Swarm..."
    - export Sql_URL="mysql://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DB_NAME?charset=utf8mb4"
    - docker stack deploy -c docker-compose.yml fastapi-stack
    - echo "Waiting for database migration to complete..."
    - sleep 30
    - docker service ls
    - docker service logs fastapi-stack_db-migration