image: docker:24.0.5

services:
  - name: docker:dind
    command: ["--insecure-registry=sggc.exploit-db.xyz:10000"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  HARBOR_URL: sggc.exploit-db.xyz:10000
  HARBOR_PROJECT: fastapi
  IMAGE_NAME: $HARBOR_URL/$HARBOR_PROJECT/fastapi

stages:
  - build
  - deploy

Fastapi_image_build:
  stage: build
  script:
    - echo "FastApi build, Dockerfile:"
    - export Sql_URL="mysql://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DB_NAME?charset=utf8mb4"
    - cat Dockerfile
    - echo $Sql_URL

    # 登录到 Harbor
    - echo $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USERNAME --password-stdin

    # 构建并打 tag 镜像
    - docker build --build-arg Sql_URL=${Sql_URL} -t $IMAGE_NAME:$CI_PIPELINE_ID .
    - docker tag $IMAGE_NAME:$CI_PIPELINE_ID $IMAGE_NAME:latest

    # 推送到 Harbor
    - docker push $IMAGE_NAME:$CI_PIPELINE_ID
    - docker push $IMAGE_NAME:latest

    - docker logout $HARBOR_URL

Fastapi_swarm_deploy:
  stage: deploy
  script:
    - echo "Deploying to Docker Swarm..."
    - export Sql_URL="mysql://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DB_NAME?charset=utf8mb4"
    - docker stack deploy -c docker-compose.yml fastapi-stack
    - echo "Waiting for database migration to complete..."
    - sleep 30
    - docker service ls
    - docker service logs fastapi-stack_db-migration