"""addpic

Revision ID: 03838bf25b55
Revises: 9947cb700365
Create Date: 2023-07-28 16:50:08.317205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '03838bf25b55'
down_revision = '9947cb700365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admintable',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('userpassword', sqlalchemy_utils.types.password.PasswordType(max_length=1094), nullable=True),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(choices=(('0', 'woman'), ('1', 'man'), ('2', 'NULL'))), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('Last_Login_Time', sa.DateTime(), nullable=True),
    sa.Column('UserUuid', sa.String(length=255), nullable=True),
    sa.Column('UserEmail', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('Typeofuser', sqlalchemy_utils.types.choice.ChoiceType(choices=(('0', 'admin'), ('1', 'editer'), ('2', 'NULL'))), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Admintable_UserId'), 'Admintable', ['UserId'], unique=False)
    op.drop_column('usertable', 'Typeofuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('Typeofuser', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True))
    op.drop_index(op.f('ix_Admintable_UserId'), table_name='Admintable')
    op.drop_table('Admintable')
    # ### end Alembic commands ###
