"""test

Revision ID: 0746105551ae
Revises: c1667e41aa7d
Create Date: 2023-07-14 11:54:45.355769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0746105551ae'
down_revision = 'c1667e41aa7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogtable', 'usertable', ['author_id'], ['UserId'])
    op.drop_column('blogtable', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('author', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True))
    op.drop_constraint(None, 'blogtable', type_='foreignkey')
    op.drop_column('blogtable', 'author_id')
    # ### end Alembic commands ###
