"""add_comment_table

Revision ID: 180b8acee31f
Revises: 53b7e7d117d5
Create Date: 2023-09-22 13:24:24.953241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b8acee31f'
down_revision = '53b7e7d117d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
