"""UserPrivileges

Revision ID: 1dbac0b0c955
Revises: 81a5bb71a9fd
Create Date: 2023-08-03 21:50:39.505900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '1dbac0b0c955'
down_revision = '81a5bb71a9fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminPrivileges',
    sa.Column('NameId', sa.Integer(), nullable=False),
    sa.Column('privilegeName', sqlalchemy_utils.types.choice.ChoiceType(choices=(('0', 'admin'), ('1', 'editer'), ('2', 'NULL'))), nullable=True),
    sa.PrimaryKeyConstraint('NameId')
    )
    op.create_index(op.f('ix_AdminPrivileges_NameId'), 'AdminPrivileges', ['NameId'], unique=False)
    op.drop_table('UserPrivileges')
    op.add_column('Admintable', sa.Column('userPrivileges', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Admintable', 'AdminPrivileges', ['userPrivileges'], ['NameId'])
    op.drop_column('Admintable', 'Typeofuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admintable', sa.Column('Typeofuser', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Admintable', type_='foreignkey')
    op.drop_column('Admintable', 'userPrivileges')
    op.create_table('UserPrivileges',
    sa.Column('NameId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('privilegeName', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.PrimaryKeyConstraint('NameId'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_AdminPrivileges_NameId'), table_name='AdminPrivileges')
    op.drop_table('AdminPrivileges')
    # ### end Alembic commands ###
