"""UserPrivileges

Revision ID: 21c7bce50e66
Revises: e6543b83b896
Create Date: 2023-08-13 21:12:09.405540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c7bce50e66'
down_revision = 'e6543b83b896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
