"""test

Revision ID: 2ebc5950aaf8
Revises: f619edf51436
Create Date: 2023-07-14 12:15:16.291806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ebc5950aaf8'
down_revision = 'f619edf51436'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogtable_ibfk_1', 'blogtable', type_='foreignkey')
    op.drop_column('blogtable', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogtable_ibfk_1', 'blogtable', 'usertable', ['author_id'], ['UserId'])
    # ### end Alembic commands ###
