"""test migration

Revision ID: 2f42612e5b5e
Revises: 87ff5bc4b336
Create Date: 2023-03-25 17:44:38.364473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f42612e5b5e'
down_revision = '87ff5bc4b336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powertable',
    sa.Column('PowerId', sa.Integer(), nullable=False),
    sa.Column('DataNum', sa.DateTime(), nullable=True),
    sa.Column('electricityNum', sa.String(length=255), nullable=True),
    sa.Column('PowerConsumption', sa.String(length=255), nullable=True),
    sa.Column('AveragePower', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PowerId')
    )
    op.create_index(op.f('ix_powertable_PowerId'), 'powertable', ['PowerId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_powertable_PowerId'), table_name='powertable')
    op.drop_table('powertable')
    # ### end Alembic commands ###
