"""UserPrivileges

Revision ID: 37a2e35daa23
Revises: 1dbac0b0c955
Create Date: 2023-08-13 19:21:33.799198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a2e35daa23'
down_revision = '1dbac0b0c955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
