"""Added account table

Revision ID: 3a2bcc686083
Revises: d6c42526764b
Create Date: 2024-01-05 15:35:18.778546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2bcc686083'
down_revision = 'd6c42526764b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
