"""addtime

Revision ID: 469c7c5b75d5
Revises: 6ce6aa752930
Create Date: 2023-07-09 22:11:04.151515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469c7c5b75d5'
down_revision = '6ce6aa752930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogtable', 'created_at')
    # ### end Alembic commands ###
