"""chareLargeBinary

Revision ID: 6ce6aa752930
Revises: 77870ec384b1
Create Date: 2023-07-05 15:58:44.642977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ce6aa752930'
down_revision = '77870ec384b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogtable', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogtable', 'content',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
