"""addpic

Revision ID: 77870ec384b1
Revises: 923779447bb9
Create Date: 2023-07-05 14:01:19.901465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77870ec384b1'
down_revision = '923779447bb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('BlogIntroductionPicture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogtable', 'BlogIntroductionPicture')
    # ### end Alembic commands ###
