"""ratingsql

Revision ID: 7fb33342b3fb
Revises: aba3909b57ee
Create Date: 2023-09-06 19:11:26.197101

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7fb33342b3fb'
down_revision = 'aba3909b57ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('device_id', sa.String(length=255), nullable=True),
                    sa.Column('blog_id', sa.String(length=255), nullable=True),
                    sa.Column('vote_count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_votes_blog_id'), 'votes', ['blog_id'], unique=False)
    op.create_index(op.f('ix_votes_device_id'), 'votes', ['device_id'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_device_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_blog_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
