"""addpic

Revision ID: 81a5bb71a9fd
Revises: 61aeec431142
Create Date: 2023-07-29 13:44:44.688701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a5bb71a9fd'
down_revision = '61aeec431142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
