"""test migration

Revision ID: 87ff5bc4b336
Revises: 
Create Date: 2023-03-22 11:16:45.229968

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '87ff5bc4b336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogtable',
    sa.Column('BlogId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BlogId')
    )
    op.create_index(op.f('ix_blogtable_BlogId'), 'blogtable', ['BlogId'], unique=False)
    op.create_table('usertable',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('userpassword', sa.String(length=255), nullable=True),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(choices=(('0', 'woman'), ('1', 'man'), ('2', 'NULL'))), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('Last_Login_Time', sa.DateTime(), nullable=True),
    sa.Column('UserUuid', sa.String(length=255), nullable=True),
    sa.Column('UserEmail', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usertable_UserId'), 'usertable', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertable_UserId'), table_name='usertable')
    op.drop_table('usertable')
    op.drop_index(op.f('ix_blogtable_BlogId'), table_name='blogtable')
    op.drop_table('blogtable')
    # ### end Alembic commands ###
