"""add_comment_table

Revision ID: a47cbb28a60b
Revises: 7fb33342b3fb
Create Date: 2023-09-22 12:47:57.457456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47cbb28a60b'
down_revision = '7fb33342b3fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.String(length=255), nullable=True),
    sa.Column('contentImg', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['usertable.UserId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_unique_constraint(None, 'votes', ['device_id', 'blog_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
