"""rating

Revision ID: aba3909b57ee
Revises: 21c7bce50e66
Create Date: 2023-09-01 21:35:34.357095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aba3909b57ee'
down_revision = '21c7bce50e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_ratings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('blog_id', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['blog_id'], ['blogtable.BlogId'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_blog_ratings_id'), 'blog_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_ratings_id'), table_name='blog_ratings')
    op.drop_table('blog_ratings')
    # ### end Alembic commands ###
