"""test

Revision ID: c1667e41aa7d
Revises: 
Create Date: 2023-07-14 11:45:22.413502

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1667e41aa7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogtable',
    sa.Column('BlogId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('BlogIntroductionPicture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('NumberLikes', sa.Integer(), nullable=True),
    sa.Column('NumberViews', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BlogId')
    )
    op.create_index(op.f('ix_blogtable_BlogId'), 'blogtable', ['BlogId'], unique=False)
    op.alter_column('usertable', 'userpassword',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               type_=sqlalchemy_utils.types.password.PasswordType(max_length=1094),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usertable', 'userpassword',
               existing_type=sqlalchemy_utils.types.password.PasswordType(max_length=1094),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_blogtable_BlogId'), table_name='blogtable')
    op.drop_table('blogtable')
    # ### end Alembic commands ###
