"""UserPrivileges

Revision ID: e6543b83b896
Revises: 37a2e35daa23
Create Date: 2023-08-13 20:15:21.694317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6543b83b896'
down_revision = '37a2e35daa23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
