"""test

Revision ID: f1d9abeef694
Revises: 2ebc5950aaf8
Create Date: 2023-07-14 12:16:34.203883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d9abeef694'
down_revision = '2ebc5950aaf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogtable', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogtable', 'author')
    # ### end Alembic commands ###
