"""add_anonymous_comments_table

Revision ID: 35578c2850c2
Revises: 4f349205aa1a
Create Date: 2025-09-25 15:42:48.410372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35578c2850c2'
down_revision = '4f349205aa1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('contentImg', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogtable.BlogId'], ),
    sa.ForeignKeyConstraint(['parentId'], ['anonymous_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_comments_id'), 'anonymous_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_comments_id'), table_name='anonymous_comments')
    op.drop_table('anonymous_comments')
    # ### end Alembic commands ###
